<a href="https://colab.research.google.com/github/PaulToronto/DataCamp---Finance-Fundamentals-in-Python/blob/main/1_3_Arrays_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.3 - Arrays in Python

In [1]:
import numpy as np

## Arrays

In [2]:
my_array = np.array([0, 1, 2, 3, 4])
my_array

array([0, 1, 2, 3, 4])

In [3]:
print(my_array)

[0 1 2 3 4]


In [4]:
type(my_array)

numpy.ndarray

In [5]:
my_array.dtype

dtype('int64')

In [6]:
my_array = np.array([3, 'is', True])
print(my_array)
my_array.dtype

['3' 'is' 'True']


dtype('<U21')

## Array operations

In [7]:
array_A = np.array([1, 2, 3])
array_B = np.array([4, 5, 6])

list_A = [1, 2, 3]
list_B = [3, 4, 5]

# element-wise vs. concatenation
array_A + array_B, list_A + list_B

(array([5, 7, 9]), [1, 2, 3, 3, 4, 5])

## Array indexing

In [8]:
months_array = np.array(['Jan', 'Feb', 'March', 'Apr', 'May'])
months_array

array(['Jan', 'Feb', 'March', 'Apr', 'May'], dtype='<U5')

In [9]:
months_array[3]

np.str_('Apr')

In [10]:
print(months_array[3])

Apr


## Array slicing

In [11]:
print(months_array[2:5])

['March' 'Apr' 'May']


## Array slicing with steps

In [12]:
print(months_array[0:5:2])

['Jan' 'March' 'May']


In [13]:
months_array[0::2]

array(['Jan', 'March', 'May'], dtype='<U5')

In [14]:
months_array[::2]

array(['Jan', 'March', 'May'], dtype='<U5')

## 2D arrays and functions

In [15]:
months = [1, 2, 3]
prices = [238.11, 237.81, 238.91]

cpi_array = np.array([months, prices])
cpi_array

array([[  1.  ,   2.  ,   3.  ],
       [238.11, 237.81, 238.91]])

In [16]:
print(cpi_array)

[[  1.     2.     3.  ]
 [238.11 237.81 238.91]]


## Array methods and properties

- `shape`: gives you the dimensions of the array
- `size`: gives you the total number of elements in the array
- `mean()`
- `std()`
- `np.arange()`
- `transpose()`

In [17]:
cpi_array.shape, cpi_array.size

((2, 3), 6)

In [18]:
np.mean(cpi_array), cpi_array.mean()

(np.float64(120.13833333333334), np.float64(120.13833333333334))

In [19]:
np.std(cpi_array), cpi_array.std()

(np.float64(118.1402002448315), np.float64(118.1402002448315))

In [20]:
np.arange(1, 13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [21]:
np.arange(4)

array([0, 1, 2, 3])

In [22]:
np.arange(1, 13, 2)

array([ 1,  3,  5,  7,  9, 11])

In [23]:
cpi_array.transpose()

array([[  1.  , 238.11],
       [  2.  , 237.81],
       [  3.  , 238.91]])

In [24]:
cpi_array

array([[  1.  ,   2.  ,   3.  ],
       [238.11, 237.81, 238.91]])

In [25]:
np.transpose(cpi_array)

array([[  1.  , 238.11],
       [  2.  , 237.81],
       [  3.  , 238.91]])

## Array indexing for 2D arrays

In [26]:
cpi_array

array([[  1.  ,   2.  ,   3.  ],
       [238.11, 237.81, 238.91]])

In [27]:
cpi_array[1, 2]

np.float64(238.91)

In [28]:
cpi_array[:, 2]

array([  3.  , 238.91])

## Using Arrays for Analysis

In [29]:
months_array = np.array(['Jan', 'Feb', 'Mar', 'Apr', 'May', 'June'])
print(months_array)

['Jan' 'Feb' 'Mar' 'Apr' 'May' 'June']


In [30]:
indexing_array = np.array([1, 3, 5])
print(indexing_array)

[1 3 5]


In [31]:
months_subset = months_array[indexing_array]
print(months_subset)

['Feb' 'Apr' 'June']


In [32]:
# example with negative indices
print(months_array)

negative_index = np.array([-1, -2])
print(negative_index)

print(months_array[negative_index])

['Jan' 'Feb' 'Mar' 'Apr' 'May' 'June']
[-1 -2]
['June' 'May']


## Boolean arrays to manipulate other arrays

In [33]:
print(months_array)

boolean_array = np.array([True, True, True, False, False, False])

print(months_array[boolean_array])

['Jan' 'Feb' 'Mar' 'Apr' 'May' 'June']
['Jan' 'Feb' 'Mar']


In [34]:
prices_array = np.array([238.11, 237.81, 238.91])
print(prices_array)

boolean_array = (prices_array > 238)
print(boolean_array)

print(prices_array[boolean_array])

[238.11 237.81 238.91]
[ True False  True]
[238.11 238.91]


In [35]:
sectors = np.array(['Information Technology', 'Health Care', 'Health Care',
                    'Information Technologies', 'Health Care'])
names = np.array(['Apple Inc', 'Abbvie Inc', 'Abbott Laboratories',
                  'Accenture Technologies', 'Allergan Plc'])

print(sectors)
print(names)

# Create boolean array
boolean_array = (sectors == 'Health Care')
print(boolean_array)

# Print only health care companies
health_care = names[boolean_array]
print(health_care)

['Information Technology' 'Health Care' 'Health Care'
 'Information Technologies' 'Health Care']
['Apple Inc' 'Abbvie Inc' 'Abbott Laboratories' 'Accenture Technologies'
 'Allergan Plc']
[False  True  True False  True]
['Abbvie Inc' 'Abbott Laboratories' 'Allergan Plc']
